version: '3.8'

services:
  weasyprint:
    build: .
    container_name: weasyprint_container
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["weasyprint"]
    stdin_open: true
