[tool.poetry]
name = "weasyprint-cli-docker"
version = "0.1.0"
description = ""
authors = ["Michael Lisitsa"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
weasyprint = "63.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
